<?php
/**
 * Base Class for all Validators. Each Validator should EXTEND this class!
 *
 *
 */
abstract class Validator {
  protected $message;

  public function __construct() {
  }

  // returns true when OK, false when not OK.
  abstract public function check($value);

  // returns the error message that was generated by the check- Method.
  public function errorMessage() {
	return $this->message;
  }
}